services:
  nginx:
    image: jonasal/nginx-certbot:6.0.1-nginx1.29.3
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./nginx-certbot.env
    configs:
      - source: indies_config
        target: /etc/nginx/user_conf.d/indies.conf
    networks:
      - public
    volumes:
      - nginx_secrets:/etc/letsencrypt
    depends_on:
      - indies-app

  indies-app:
    image: indies-app

    build:
      context: .
      dockerfile: Dockerfile
    container_name: indies-app
    env_file:
      - .env.production.local
    networks:
      - private
      - public
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:17.2-alpine3.20
    conatainer_name: postgres
    restart: always
    env_file:
      - .env.production.local
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - private

configs:
  indies_config:
    file: ./indies.conf

networks:
  public:

  private:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/19"
          gateway: "10.0.0.1"

volumes:
  postgres-data:
  nginx_secret:
