services:
  nginx:
    image: jonasal/nginx-certbot:6.0.1-nginx1.29.3
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./deploy/nginx/nginx-certbot.env
    configs:
      - source: indies_config
        target: /etc/nginx/user_conf.d/indies.conf
    networks:
      - public
    volumes:
      - nginx_secrets:/etc/letsencrypt
    depends_on:
      - indies-app

  indies-app:
    image: indies-app

    build:
      context: .
      dockerfile: Dockerfile
    container_name: indies-app
    env_file:
      - .env.production
    networks:
      - private
      - public
    depends_on:
      - postgres
    restart: always
    volumes:
      - uploads-data:/app/public/uploads

  postgres:
    image: postgres:17.2-alpine3.20
    container_name: postgres
    restart: always
    env_file:
      - .env.production
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /var/lib/postgres-certs/server.crt:/var/lib/postgresql/server.crt:ro
      - /var/lib/postgres-certs/server.key:/var/lib/postgresql/server.key:ro
    networks:
      - private
    command:
      # Pass configuration flags to enable SSL and specify certificate files
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key

configs:
  indies_config:
    file: ./deploy/nginx/indies.conf

networks:
  public:

  private:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/19"
          gateway: "10.0.0.1"

volumes:
  postgres-data:
  nginx_secrets:
  uploads-data:
