services:
  app:
    image: indies-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: indies-app
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    restart: unless-stopped
