services:
  nginx:
    image: nginx:1.29
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
      - ./nginx:/etc/nginx/conf.d
    networks:
      - public
      - private

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    entrypoint: >
      sh -c "
      if [ \"$CERTBOT_ENV\" = \"staging\" ]; then
        echo 'ðŸ§ª Using Letâ€™s Encrypt STAGING';
        STAGING_FLAG='--staging';
      else
        echo 'ðŸ”’ Using Letâ€™s Encrypt PRODUCTION';
        STAGING_FLAG='';
      fi;

      certbot certonly \
        --webroot \
        -w /var/www/certbot \
        -d $CERTBOT_DOMAIN \
        --email $CERTBOT_EMAIL \
        --agree-tos \
        --no-eff-email \
        $STAGING_FLAG
      "
    networks:
      - public

  postgres:
    image: postgres:17.2-alpine3.20
    container_name: postgres
    restart: always
    env_file:
      - .env.production
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./certs:/certs:ro
    command: -c ssl=on
      -c ssl_cert_file=/certs/server.crt
      -c ssl_key_file=/certs/server.key
      -c ssl_ca_file=/certs/root.crt
    networks:
      - private

networks:
  public:
  private:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/19"
          gateway: "10.0.0.1"

volumes:
  postgres-data:
  nginx_secrets:
  certbot-webroot:
