services:
  nginx:
    image: nginx:1.29
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
      - ./nginx:/etc/nginx/conf.d
    networks:
      - public
      - private

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    env_file:
      - .env.production
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    entrypoint: >
      sh -c '
      trap exit TERM;
      while :; do
        if [ "$$CERTBOT_ENV" = "staging" ]; then
          STAGING_FLAG="--staging";
        else
          STAGING_FLAG="";
        fi;

        certbot renew $$STAGING_FLAG --quiet;
        sleep 12h;
      done
      '
    depends_on:
      - nginx
    networks:
      - public

  postgres:
    image: postgres:17.2-alpine3.20
    container_name: postgres
    restart: always
    env_file:
      - .env.production
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command:
      - "-c"
      - "ssl=on"
      - "-c"
      - "ssl_cert_file=/var/lib/postgresql/data/certs/server.crt"
      - "-c"
      - "ssl_key_file=/var/lib/postgresql/data/certs/server.key"
      - "-c"
      - "ssl_ca_file=/var/lib/postgresql/data/certs/root.crt"
    networks:
      - private

networks:
  public:
  private:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/19"
          gateway: "10.0.0.1"

volumes:
  postgres-data:
  nginx_secrets:
  certbot-webroot:
