services:
  indies-app:
    image: indies-app:latest
    container_name: indies-app
    restart: always

    env_file:
      - .env.production
    networks:
      - private
    volumes:
      - uploads-data:/app/public/uploads

networks:
  private:
    external: true

volumes:
  uploads-data:
