services:
  postgres:
    image: postgres:17.2-alpine3.20
    container_name: postgres
    restart: always
    env_file:
      - .env.production
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-certs:/etc/postgres/certs:ro
    command:
      - "-c"
      - "ssl=on"
      - "-c"
      - "ssl_cert_file=/etc/postgres/certs/server.crt"
      - "-c"
      - "ssl_key_file=/etc/postgres/certs/server.key"
      - "-c"
      - "ssl_ca_file=/etc/postgres/certs/root.crt"
    networks:
      - private

  indies-app:
    image: indies-app:latest
    container_name: indies-app
    restart: always
    env_file:
      - .env.production
    volumes:
      - uploads-data:/app/public/uploads
      - postgres-certs:/etc/ssl/postgres
    depends_on:
      - postgres
    networks:
      - private

  nginx:
    image: nginx:1.29
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - nginx_secrets:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    networks:
      - public
      - private

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    env_file:
      - .env.production
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: >
      sh -c '
      trap exit TERM;
      while :; do
        certbot renew --quiet;
        sleep 12h;
      done
      '
    networks:
      - public

networks:
  private:
  public:

volumes:
  postgres-data:
  postgres-certs:
  uploads-data:
  nginx_secrets:
  certbot-webroot:
